# Generated by Django 6.0.6 on 2026-07-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_waste_management_app', '0003_complaint_after_image_complaint_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='citizen_profiles/'),
        ),
    ]
