# Generated by Django 6.0.6 on 2026-07-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_waste_management_app', '0004_userprofile_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='training_dataset/')),
                ('label', models.CharField(choices=[('Plastic', 'Plastic'), ('Paper', 'Paper'), ('Organic', 'Organic'), ('Metal', 'Metal'), ('Glass', 'Glass'), ('Cardboard', 'Cardboard')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
