# Generated by Django 6.0.6 on 2026-07-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_waste_management_app', '0007_alter_complaint_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(blank=True, choices=[('Plastic', 'Plastic'), ('Paper', 'Paper'), ('BIODEGRADABLE', 'BIODEGRADABLE'), ('Metal', 'Metal'), ('Glass', 'Glass'), ('ELECTRONIC WASTE', 'ELECTRONIC WASTE')], max_length=20, null=True),
        ),
    ]
