# Generated by Django 6.0.6 on 2026-07-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_waste_management_app', '0008_alter_complaint_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(blank=True, choices=[('PLASTIC', 'PLASTIC'), ('PAPER', 'PAPER'), ('BIODEGRADABLE', 'BIODEGRADABLE'), ('METAL', 'METAL'), ('GLASS', 'GLASS'), ('ELECTRONIC WASTE', 'ELECTRONIC WASTE'), ('CARDBOARD', 'CARDBOARD')], max_length=20, null=True),
        ),
    ]
