# Generated by Django 6.0.6 on 2026-07-14 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_waste_management_app', '0009_alter_complaint_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetitem',
            name='image',
            field=models.ImageField(max_length=255, upload_to='training_dataset/'),
        ),
    ]
